### PR TITLE
First attempt at modularising the codebase

### PR DESCRIPTION
**Pull request by nertpinx**
Tests with `tox` run fine, but it would be nice to have a way to test this in a
more complete manner.

This is based on top of #55.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by nertpinx** [comment]
ci test please

**Comment by nertpinx** [comment]
ci add to whitelist

**Comment by nertpinx** [comment]
@nyoxi I fixed it! And now  There was one part intended in a wrong fashion which made the code do something completely different. Yay for python refactors, I guess =) Anyway, as I said, I tested it, but only for VDSMHost and I haven't gone through all the changes to check that the indentation is actually completely fixed.

**Comment by nertpinx** [comment]
Also looks like this one needs to be tested by the ci as well and I apparently (see old comments) do not have a way to trigger it.

**Comment by nyoxi** [comment]
ci test please

**Review by nyoxi — APPROVED** [review]

**Pull request merged**
