### PR TITLE
Refactor role for UCI

### PR DESCRIPTION
**Pull request by ghost**
With Universal Conversion Image (UCI) being built, we need to refactor the oVirt.v2v-conversion-host role to remove most of the tasks not related to transport method and SSL configuration. Indeed, the conversion hosts based on UCI will use kubevirt-conversion containers to perform the VM conversion, rather than virt-v2v installed via packages.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by nyoxi** [comment]
This will break the deployment for the existing setups that will not employ the UCI. Is that really what we want? On the other hand I'm not sure how difficult it will be to keep supporting both use cases.

**Comment by ghost** [comment]
Yes, either the playbook would have to find out that it's a UCI-based conversion host, or there should be an extra variable passed by the playbook caller, i.e. ManageIQ. It's the same problem we had in the past and why we created compatibility matrix for CloudForms / v2v-conversion-host-ansible versions.

**Comment by nertpinx** [comment]
Maybe you could create two different playbooks that would just use different tasks/roles so that the code is not duplicated, but it's still easy to use in both scenarios.

**Comment by ghost** [comment]
Closing in favor of https://github.com/ManageIQ/manageiq-v2v-conversion_host/pull/1

**Pull request closed without merging**
