### PR TITLE
[RFR]Updating correct role name in examples

### PR DESCRIPTION
**Pull request by kedark3**
Running playbooks I realized role name from ansible galaxy didn't match examples. Please review and let me know your  thoughts on the corrected role name.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by mykaul** [comment]
@nyoxi - is the role developed here, or in oVirt's Gerrit?

**Comment by eedri** [comment]
ci test please

**Comment by nyoxi** [comment]
@kedark3 Good catch. This is inconsistency between the naming we use in RPMs and what's in the Galaxy. I need to figure out how to fix that in Galaxy.

@mykaul It is developed here. The Gerrit patch has been dropped.

**Comment by nyoxi** [comment]
@kedark3 I have updated the name in Galaxy so I'm closing this.

**Comment by kedark3** [comment]
@nyoxi Thanks for the update :100: :clinking_glasses:

**Pull request closed without merging**
